<script>
    require(['jquery','Evince_CourierManager/js/select2','Evince_CourierManager/js/select2.min'], function($) {
        $(document).ready(function () {
	        setTimeout(function(){	
	        	jQuery('.select').select2();
	        }, 15000);	
          });
    });

</script>
<style type="text/css">
    body.checkout-index-index .checkout-block.-summary .payment-methods .actions-toolbar .primary{display: block !important;}
    button#checkoutOrder {display: none !important;}
</style>