<?php
// @codingStandardsIgnoreFile

/** @var $block \Magento\Catalog\Block\Product\View */
?>
<?php $_product = $block->getProduct(); ?>
<?php
$buttonTitle = __('Add to Cart');
$outOfStockTitle = __('Out of Stock');
$goToProductTitle = __('Go To Product');?>
<?php /*
$wishlistPost = json_decode($this->helper('Magento\Wishlist\Helper\Data')->getAddParams($_product),true);
$wishListAction  =   $wishlistPost["action"];
*/ ?>

<div class="qty-price-section">
	<div class="qty-price">
		<label for="qty"><span><?= /* @escapeNotVerified */ __('Qty') ?></span></label>
			<input type="number"
				   name="qty"
				   id="qty"
				   value="<?= /* @escapeNotVerified */ $block->getProductDefaultQty() * 1 ?>"
				   title="<?= /* @escapeNotVerified */ __('Qty') ?>"
				   class="input-text qty"
				   data-validate="<?= $block->escapeHtml(json_encode($block->getQuantityValidators())) ?>"
				   />
		<span><?php echo $this->getChildHtml('product.info.price'); ?><?php echo $this->getChildHtml('product.info.price.new'); ?></span>
	</div>
</div>
<div class="box-tocart quick-view-cart">
    <div class="fieldset">
        <div class="actions">
            <?php if ($_product->isSaleable()): ?>
                <button type="submit"
                        title="<?php /* @escapeNotVerified */ echo $buttonTitle ?>"
                        class="btn btn-primary"
                        id="product-addtocart-button">
                    <span><?php /* @escapeNotVerified */ echo $buttonTitle ?></span>
                </button>
            <?php else: ?>
                <button type="button" name="out_of_stock"
                        title="<?= /* @escapeNotVerified */ $outOfStockTitle ?>"
                        class="btn btn-secondary"
                        id="">
                    <span><?= /* @escapeNotVerified */ $outOfStockTitle ?></span>
                </button>
            <?php endif; ?>
            <?php echo $block->getChildHtml('', true) ?>
        </div>
    </div>
</div>

<?php if ($block->isRedirectToCartEnabled()) : ?>
    <script type="text/x-magento-init">
    {
        "#product_addtocart_form": {
            "Magento_Catalog/product/view/validation": {
                "radioCheckboxClosest": ".nested"
            }
        }
    }
</script>
<?php else : ?>
    <script>
        require([
            'jquery',
            'mage/mage',
            'Magento_Catalog/product/view/validation',
            'Magento_Catalog/js/catalog-add-to-cart'
        ], function ($) {
            'use strict';

            $('#product_addtocart_form').mage('validation', {
                radioCheckboxClosest: '.nested',
                submitHandler: function (form) {
                    var widget = $(form).catalogAddToCart({
                        bindSubmit: false
                    });

                    widget.catalogAddToCart('submitForm', $(form));

                    return false;
                }
            });
        });
    </script>
<?php endif; ?>
<script type="text/javascript">
require(['jquery'],function($){
    $(document).on('click','.change-qtys',function(){
        var myobj = $(this).parent().find('input[type=number]');
        var currentVal = parseInt(myobj.val());

        if($(this).hasClass('minus-price')){
            if(myobj.val() > 1){
                myobj.val(currentVal-1);
            }else{
                myobj.val(1);
            }
        }else{
            if(currentVal >= 1){
                myobj.val(currentVal+1);
            }else{
                myobj.val(1);
            }
        }
    });
    $(document).ready(function() {
        $('body').addClass("intro-quick-view");
    });
});
</script>
<script type="text/javascript">
require(['jquery'],function($){
	$(document).on('keyup','#qty',function(e){
		if($(this).val() < 1) {
			//$("#qty-error-cls").html("Please enter the quantity is greater then 0.");
			$(this).val(1).trigger('change');
		}
		if($(this).val() > 12 ) {
			//$("#qty-error-cls").html("Please enter the quantity is greater then 0.");
			$(this).val(1).trigger('change');
		}
	});
 jQuery('.numbersOnly').keyup(function () { 
    this.value = this.value.replace(/[^0-9\.]/g,'');
});

	$(document).ready(function() {
	  $('input').on('drop', function() {
		return false;
	  });
	});
});
</script>
<script> 
 require(['jquery'],function($){
jQuery(document).ready(function(){
	jQuery(".custom_action").click(function(event){
		event.stopPropagation();
		event.preventDefault();
		if(jQuery('#product_addtocart_form').valid())
		{
			if(jQuery("#product_detail_wish_list").length == 0){
				jQuery('<div id="whishLishFormContainer" style="display:none;"></div>').appendTo('body');
				jQuery('<form action="<?php echo $wishListAction; ?>" id="product_detail_wish_list" target="_top"></form>').appendTo(jQuery('#whishLishFormContainer'));
			} 	
			var formHtml = "";
			jQuery('#product_addtocart_form input[type=text],#product_addtocart_form input[type=hidden],#product_addtocart_form select').each(function(index,field){
				formHtml += "<input type='hidden' name='"+jQuery(field).attr("name")+"' value='"+jQuery(field).attr("value")+"' /> ";
			})
			jQuery('#product_addtocart_form input[type=checkbox],#product_addtocart_form  input[type=radio]').each(function(index,field){
				if(jQuery(field).is(':checked')){
					formHtml += "<input type='hidden' name='"+jQuery(field).attr("name")+"' value='"+jQuery(field).attr("value")+"' /> ";
				}
			})
			
			
			
			jQuery("#product_detail_wish_list").html(formHtml);
			jQuery("#product_detail_wish_list").submit();
		}
		else
		{
			return false;
		}
	});
});
}); 
</script>
