<?php
$at_settings	 = $block->getConfig( 'athlete2_settings/above_footer_block2' );
if ( $at_settings[ 'show_block' ] && $block->isCurrentPage( $at_settings[ 'above_footer_block_location' ] ) ) {
	?>
	<div class="above-footer-content2">
		<?php
		if ( $at_settings[ 'above_footer_block_type' ] == 'textfield' ) {
			echo $block->getBlockTemplateProcessor( $at_settings[ 'above_footer_block_custom' ] );
		} else {
			echo $this->getLayout()->createBlock( 'Magento\Cms\Block\Block' )->setBlockId( $at_settings[ 'above_footer_block_static' ] )->toHtml();
		}
		?>
	</div>	
<?php } ?>
