<?php
echo $this->getChildHtml( 'ox_bottom_nav_css' );
echo $this->getChildHtml( 'ox_bottom_nav_home' );
echo $this->getChildHtml( 'ox_bottom_nav_menu' );
echo $this->getChildHtml( 'ox_bottom_nav_search' );
echo $this->getChildHtml( 'ox_bottom_nav_custom' );
echo $this->getChildHtml( 'ox_bottom_nav_catalog' );
echo $this->getChildHtml( 'ox_bottom_nav_account' );
echo $this->getChildHtml( 'ox_bottom_nav_compare' );
echo $this->getChildHtml( 'ox_bottom_nav_wishlist' );
echo $this->getChildHtml( 'ox_bottom_nav_minicart' );
echo $this->getChildHtml( 'ox_bottom_nav_js' );