<div class="iwd-locked-feature admin__field">
    <div class="page-main-actions _hidden">
        <div class="page-actions" data-ui-id="page-actions-toolbar-content-header">
            <div class="page-actions-inner" data-title="Sources">
                <div class="page-actions-buttons">
                    <button id="add" title="Return to Order Management" type="button"
                            class="action-default scalable add primary"
                            onclick="setLocation('#')"
                            data-ui-id="go-to-orders-button">
                        <span>Return to Order Management</span>
                    </button>
                </div>
            </div>
        </div>
    </div>
    <div id="page:main-container" class="page-columns">
        <div class="admin__old">
            <div id="container" class="main-col">
                <div id="source" data-grid-id="source">
                    <div class="admin__data-grid-header admin__data-grid-toolbar">
                        <div class="_massaction admin__data-grid-header-row">
                            <div id="source_massaction" class="admin__grid-massaction">
                                <div class="no-display">
                                    <div id="source_massaction-item-disable-block"></div>
                                </div>
                            </div>
                            <div class="admin__control-support-text">
                                <span id="source-total-count"
                                      data-ui-id="ordermanager-warehouse-source-grid-total-count">143</span>
                                records found <span id="source_massaction-count" class="mass-select-info _empty"><strong
                                            data-role="counter">0</strong> <span>selected</span></span>
                            </div>
                            <div class="admin__data-grid-pager-wrap">
                                <select name="limit" id="source_page-limit"
                                        data-ui-id="ordermanager-warehouse-source-grid-per-page"
                                        class="admin__control-select">
                                    <option value="20" selected="selected">20</option>
                                    <option value="30">30</option>
                                    <option value="50">50</option>
                                    <option value="100">100</option>
                                    <option value="200">200</option>
                                </select>
                                <label for="source_page-limit" class="admin__control-support-text">per page</label>
                                <div class="admin__data-grid-pager">
                                    <button type="button" class="action-previous disabled"><span>Previous page</span>
                                    </button>
                                    <input type="text" id="source_page-current" name="page" value="1"
                                           class="admin__control-text"
                                           data-ui-id="ordermanager-warehouse-source-grid-current-page">
                                    <label class="admin__control-support-text" for="source_page-current">
                                        of <span>1</span> </label>
                                    <button type="button" class="action-next disabled"><span>Next page</span></button>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="admin__data-grid-wrap admin__data-grid-wrap-static">
                        <div class="admin__data-grid-wrap">
                            <table class="data-grid data-grid-draggable">
                                <thead>
                                <tr>
                                    <th class="data-grid-th _sortable _draggable">
                                        <span class="data-grid-cell-content">Admin Name</span>
                                    </th>
                                    <th class="data-grid-th _sortable _draggable">
                                        <span class="data-grid-cell-content">Order ID</span>
                                    </th>
                                    <th class="data-grid-th _sortable _draggable">
                                        <span class="data-grid-cell-content">Description</span>
                                    </th>
                                    <th class="data-grid-th _sortable _draggable _ascend">
                                        <span class="data-grid-cell-content">Date</span>
                                    </th>
                                    <th class="data-grid-th">
                                        <span class="data-grid-cell-content">Action</span>
                                    </th>
                                </tr>
                                </thead>
                                <tbody>
                                <tr class="data-row">
                                    <td>
                                        <div class="data-grid-cell-content"></div>
                                    </td>
                                    <td>
                                        <div class="data-grid-cell-content"></div>
                                    </td>
                                    <td>
                                        <div class="data-grid-cell-content">
                                            Congratulations! IWD's Order Manager was installed successfully.
                                        </div>
                                    </td>
                                    <td>
                                        <div class="data-grid-cell-content">Sep 24, 2016 10:13:40 PM</div>
                                    </td>
                                    <td class="data-grid-actions-cell"></td>
                                </tr>
                                <tr class="data-row _odd-row">
                                    <td>
                                        <div class="data-grid-cell-content">Admin User</div>
                                    </td>
                                    <td>
                                        <div class="data-grid-cell-content">000000003</div>
                                    </td>
                                    <td>
                                        <div class="data-grid-cell-content">
                                            Order customer information was changed:<br>
                                            --- Customer email was changed from "roni_cost@example.com" to
                                            "test@test.com"<br>
                                            --- First name was changed from "Veronica" to "test"<br>
                                            --- Last name was changed from "Costello" to "test"<br>
                                            Customer was changed from "Veronica Costello" to "test test"<br>
                                        </div>
                                    </td>
                                    <td>
                                        <div class="data-grid-cell-content">Oct 6, 2016 4:54:18 PM</div>
                                    </td>
                                    <td class="data-grid-actions-cell">
                                        <a class="action-menu-item" href="#">View Order</a>
                                    </td>
                                </tr>
                                <tr class="data-row _odd-row">
                                    <td>
                                        <div class="data-grid-cell-content">Admin User</div>
                                    </td>
                                    <td>
                                        <div class="data-grid-cell-content">000000003</div>
                                    </td>
                                    <td>
                                        <div class="data-grid-cell-content">
                                            Order customer information was changed:<br>
                                            --- First name was changed from "test" to "test1"
                                        </div>
                                    </td>
                                    <td>
                                        <div class="data-grid-cell-content">Oct 6, 2016 5:13:48 PM</div>
                                    </td>
                                    <td class="data-grid-actions-cell">
                                        <a class="action-menu-item" href="#">View Order</a>
                                    </td>
                                </tr>
                                <tr class="data-row _odd-row">
                                    <td>
                                        <div class="data-grid-cell-content">Admin User</div>
                                    </td>
                                    <td>
                                        <div class="data-grid-cell-content">000000003</div>
                                    </td>
                                    <td>
                                        <div class="data-grid-cell-content">
                                            Order customer information was changed:<br>
                                            --- Customer email was changed from
                                            "test@test.com" to "roni_cost@example.com"<br>
                                            --- First name was changed from "test1" to "Veronica"<br>
                                            --- Last name was changed from "test" to "Costello"<br>
                                            Customer was changed from "test test" to "Veronica Costello"
                                        </div>
                                    </td>
                                    <td>
                                        <div class="data-grid-cell-content">Oct 6, 2016 5:18:48 PM</div>
                                    </td>
                                    <td class="data-grid-actions-cell">
                                        <a class="action-menu-item" href="#">View Order</a>
                                    </td>
                                </tr>
                                <tr class="data-row _odd-row">
                                    <td>
                                        <div class="data-grid-cell-content">Admin User</div>
                                    </td>
                                    <td>
                                        <div class="data-grid-cell-content">000000001</div>
                                    </td>
                                    <td>
                                        <div class="data-grid-cell-content">
                                            Order customer information was changed:<br>
                                            --- Customer email was changed from
                                            "roni_cost@example.com" to "test@test.com"<br>
                                            --- First name was changed from "Veronica" to "test"<br>
                                            --- Last name was changed from "Costello" to "test"<br>
                                            Customer was changed from "Veronica Costello" to "test test"
                                        </div>
                                    </td>
                                    <td>
                                        <div class="data-grid-cell-content">Oct 7, 2016 5:51:27 PM</div>
                                    </td>
                                    <td class="data-grid-actions-cell">
                                        <a class="action-menu-item" href="#">View Order</a>
                                    </td>
                                </tr>
                                <tr class="data-row" data-repeat-index="14">
                                    <td>
                                        <div class="data-grid-cell-content">Admin User</div>
                                    </td>
                                    <td>
                                        <div class="data-grid-cell-content">000000001</div>
                                    </td>
                                    <td>
                                        <div class="data-grid-cell-content">
                                            Order customer information was changed:<br>
                                            --- Customer email was changed from
                                            "test@test.com" to "roni_cost@example.com"<br>
                                            --- First name was changed from "test" to "Veronica"<br>
                                            --- Last name was changed from "test" to "Costello"<br>
                                            Customer was changed from "test test" to "Veronica Costello"
                                        </div>
                                    </td>
                                    <td>
                                        <div class="data-grid-cell-content">Oct 7, 2016 5:56:05 PM</div>
                                    </td>
                                    <td class="data-grid-actions-cell">
                                        <a class="action-menu-item" href="#">View Order</a>
                                    </td>
                                </tr>
                                <tr class="data-row _odd-row">
                                    <td>
                                        <div class="data-grid-cell-content">Admin User</div>
                                    </td>
                                    <td>
                                        <div class="data-grid-cell-content">000000001</div>
                                    </td>
                                    <td>
                                        <div class="data-grid-cell-content">
                                            Order customer information was changed:<br>
                                            --- Customer email was changed from
                                            "roni_cost@example.com" to "test@test.com"<br>
                                            --- First name was changed from "Veronica" to "test"<br>
                                            --- Last name was changed from "Costello" to "test"<br>
                                            Customer was changed from "Veronica Costello" to "test test"
                                        </div>
                                    </td>
                                    <td>
                                        <div class="data-grid-cell-content">Oct 7, 2016 5:58:42 PM</div>
                                    </td>
                                    <td class="data-grid-actions-cell">
                                        <a class="action-menu-item" href="#">View Order</a>
                                    </td>
                                </tr>
                                <tr class="data-row" data-repeat-index="16">
                                    <td>
                                        <div class="data-grid-cell-content">Admin User</div>
                                    </td>
                                    <td>
                                        <div class="data-grid-cell-content">000000001</div>
                                    </td>
                                    <td>
                                        <div class="data-grid-cell-content">
                                            Order customer information was changed:<br>
                                            --- Customer email was changed from
                                            "test@test.com" to "roni_cost@example.com"
                                        </div>
                                    </td>
                                    <td>
                                        <div class="data-grid-cell-content">Oct 7, 2016 6:03:42 PM</div>
                                    </td>
                                    <td class="data-grid-actions-cell">
                                        <a class="action-menu-item" href="#">View Order</a>
                                    </td>
                                </tr>
                                <tr class="data-row _odd-row">
                                    <td>
                                        <div class="data-grid-cell-content">Admin User</div>
                                    </td>
                                    <td>
                                        <div class="data-grid-cell-content">000000001</div>
                                    </td>
                                    <td>
                                        <div class="data-grid-cell-content">
                                            Order customer information was changed:<br>
                                            --- First name was changed from "test" to "Veronic"<br>
                                            --- Last name was changed from "test" to "Costello"<br>
                                            Customer was changed from "test test" to "Veronica Costello"<br>
                                        </div>
                                    </td>
                                    <td>
                                        <div class="data-grid-cell-content">Oct 7, 2016 6:07:09 PM</div>
                                    </td>
                                    <td class="data-grid-actions-cell">
                                        <a class="action-menu-item" href="#">View Order</a>
                                    </td>
                                </tr>
                                <tr class="data-row">
                                    <td>
                                        <div class="data-grid-cell-content">Admin User</div>
                                    </td>
                                    <td>
                                        <div class="data-grid-cell-content">000000001</div>
                                    </td>
                                    <td>
                                        <div class="data-grid-cell-content">
                                            Order customer information was changed:<br>
                                            --- Customer email was changed from
                                            "roni_cost@example.com" to "test@test.com"<br>
                                            --- First name was changed from "Veronic" to "test"<br>
                                            --- Last name was changed from "Costello" to "test"<br>
                                            Customer was changed from "Veronica Costello" to "test test"
                                        </div>
                                    </td>
                                    <td>
                                        <div class="data-grid-cell-content">Oct 7, 2016 6:08:55 PM</div>
                                    </td>
                                    <td class="data-grid-actions-cell"></td>
                                </tr>
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="iwd-lock-pro"></div>
    <div class="iwd-unlock-pro iwd-upgrade-to-pro"><i class="fa fa-lock"></i><?php echo __('Unlock Pro') ?></div>
</div>

<script type="text/javascript">
    // <![CDATA[
    require(["IWD_OrderManager/js/upgrade"],
        function (iwdOrderManagerUpgrade) {
            var orderManagerUpgrade = new iwdOrderManagerUpgrade();
            orderManagerUpgrade.init();
        }
    );
    // ]]>
</script>