<div class="all-track-info">
  <section class="track-order-step-section">
    <div class="">
      <h2 class="track-order-step-text-center-main"><?php echo __('Track Your Order Step By Step') ?></h2>
    </div>
  </section>

  <section>
    <div class="container-search-box">
      <p class="text-left"><?php echo __('Order number'); ?></p>
      <div class="row">
        <div class="col-md-12">
          <form class="track-number-form" method="get" action="<?php echo $this->getUrl('ordertrack'); ?>">
            <input type="text" placeholder="<?php echo __('Your order number') ?>"
              value="<?php echo $block->getOrderNumber() ?>" name="order_id">
            <button type="submit"><?php echo __('Track') ?></button>
          </form>
          <br>
        </div>
      </div>
      <?php if ($block->getOrderNumber()): ?>
        <?php $order = $block->getOrderSearch(); ?>
        <?php if ($order): ?>
          <?php if ($order->getId()): ?>
            <?php echo $this->getLayout()->createBlock("Developerswing\OrderTracking\Block\Index\Index")->setTemplate("Developerswing_OrderTracking::index/ordertrack.phtml")->toHtml() ?>
          <?php else: ?>
            <div class="not-found"><?php echo __('Order not found or invalid ID 11') ?></div>
          <?php endif; ?>
        <?php else: ?>
          <div class="not-found"><?php echo __('Order not found') ?></div>
        <?php endif; ?>
      <?php endif; ?>
  </section>
</div>