<?php
$helper = $this->helper('MGS\Brand\Helper\Data');
$params = $this->getRequest()->getParams();
?>
<div class="search search_article">
    <form id="search_brand_form" action="" method="get">
		<input id="search_brand"
			   type="text"
			   name="keyword"
			   value="<?php if (isset($params['keyword'])) { echo $params['keyword']; } ?>"
			   placeholder="<?php echo __('Search brand here...'); ?>"
			   class="form-control"
			   autocomplete="off"/>
		<?php /* if (isset($params['char']) && $params['char'] != ''): ?>
			<input id="search_brand_by_char"
				   type="hidden"
				   name="char"
				   value="<?php echo $params['char']; ?>"/>
		<?php endif; */ ?>
		
		<?php /* 
		<a href="javascript:void(0)" onClick="submitDetailsForm()" class="action search"><img src="<?php echo $block->getViewFileUrl('Mageprince_Faq::images/search-img.png'); ?>" alt="img"></a>
		*/ ?>
		
		<button type="submit"
				title="<?php echo $block->escapeHtml(__('Search')) ?>"
				class="action search">
					<img src="<?php echo $block->getViewFileUrl('Mageprince_Faq::images/search-img.png'); ?>" alt="img">
		</button>
		
		<?php /* if (isset($params['keyword']) || isset($params['char'])): ?>
			<button type="button"
					onclick="window.location.href='<?php echo $helper->getBrandUrl(); ?>'"
					title="<?php echo $block->escapeHtml(__('Reset Filter')) ?>"
					class="action search">
				<span><?php echo __('Reset Filter'); ?></span>
			</button>
		<?php endif; */ ?>
    </form>
</div>
<script>
/* function submitDetailsForm() {
	alert("hello");
   jQuery("#search_brand").submit();
} */
/* require(['jquery'],function($){
	$( ".action.search" ).click(function() {
	  $( "#search_brand" ).submit();
	});
}); */
</script>