<?php
/**
 * @copyright Copyright (c) 2017 www.tigren.com
 * @var \Tigren\Ajaxwishlist\Block\Js $block
 */
/** @var Tigren\Ajaxwishlist\Helper\Data $helper */
$helper = $this->helper('Tigren\Ajaxwishlist\Helper\Data');
?>
<?php if($helper->isEnabledAjaxWishlist()): ?>
<script type="text/x-magento-init">
{
    "*": {
        "tigren/ajaxwishlist"    : <?php echo $block->getAjaxWishlistInitOptions(); ?>,
        "tigren/ajaxremove" : ""
    }
}

</script>
<?php endif; ?>