<?php
/**
 * Athlete2 Theme
 *
 * @author      Olegnax
 * @package     Olegnax_Athlete2
 * @copyright   Copyright (c) 2023 Olegnax (https://olegnax.com). All rights reserved.
 * @license     https://www.olegnax.com/license
 */

// @codingStandardsIgnoreFile

/**
 * Product list template
 *
 * @var $block ListProduct
 */

use Magento\Catalog\Block\Product\ListProduct;

?>
<div data-move-mobile="filtersslideout" data-role="OXmodal"
             data-mage-init='{"OXmodal":{
                "triggerTarget":".filters-action",
				"overlayClass":"ox-slideout-shadow",
                "timeout": "500",
                "closeOnEscape": true,
				"positionSlideout": "left",
				"hoverOpen": true,
				"type": "slideout",
				"htmlClass":"ox-fixed"
			}}'><!-- filters --></div>
