<div id="shipping-result-form">
    <div class="iwd-locked-feature">
        <form id="shipping-form">
            <?php echo $block->getShippingForm(); ?>
            <?php echo $block->getActionsForm(); ?>
        </form>
        <div class="iwd-lock-pro"></div>
        <div class="iwd-unlock-pro iwd-upgrade-to-pro"><i class="fa fa-lock"></i><?php echo __('Unlock Pro') ?></div>
    </div>
</div>