<?php
//@codingStandardsIgnoreFile
/** @var \Mirasvit\Helpdesk\Block\Adminhtml\Ticket\Edit\Tab\General $block */
/** @var \Mirasvit\Helpdesk\Model\Ticket $ticket */
$ticket = $block->getTicket();
$subjectHelper = $this->helper('Dakha\CustomWork\Helper\Data');
?>
<input type="hidden" name="ticket_id" value="<?= $ticket->getId() ?>">

<input type="hidden" name="reply_type" value="">

<div class="page-layout-admin-2columns-left" data-mage-init='{"ticketEditPage":{}}'>
    <div data-role="spinner" class="admin__data-grid-loading-mask">
        <div class="spinner">
            <span></span><span></span><span></span><span></span>
            <span></span><span></span><span></span><span></span>
        </div>
    </div>

    <div class="page-columns">
        <div class="side-col" id="page:left">

            <?= $block->getCustomerSummaryHtml() ?>

            <div class="clearfix"></div>
            <div class="ticket-summary">
                <div class="section">
                    <div class="admin__fieldset-wrapper-title" tabindex="3">
                        <strong class="title">
                            <span><?= __('Ticket Summary') ?></span>
                        </strong>
                    </div>
                    <?php if ($ticket->getAdminUser()): ?>
                    <div class="admin__field">
                            <label class="admin__field-label" for="admin_user">
                                <span><?= __('Created By') ?></span>
                            </label>
                            <div class="admin__field-control">
                                <span><?= $ticket->getAdminUser() ?></span>
                            </div>
                    </div>
                    <?php endif;?>
                    <?php if (!$ticket->getId()): ?>
                        <?php if($subjectHelper->getSubjects()):?>
                        <div class="admin__field _required">
                            <label class="admin__field-label" for="subject">
                                <span><?= __('Subject') ?></span>
                            </label>
                            <div class="admin__field-control">
                                <select name="subject" class="required">
                                <?php foreach($subjectHelper->getSubjects() as $subject):?>
                                   <option value="<?= $subject['english']?>"><?= $subject['english']?></option>
                                <?php endforeach;?>
                                </select>       
                            </div>
                        </div>    
                        <?php else:?>
                        <div class="admin__field _required">
                            <label class="admin__field-label" for="subject">
                                <span><?= __('Subject') ?></span>
                            </label>
                            <div class="admin__field-control">
                                <input type="text" name="subject" class="required" placeholder="enter subject of ticket"
                                       value="<?php $ticket->getSubject() ?>">
                            </div>
                        </div>    
                        <?php endif;?>    
                        
                    <?php else: ?>
                        <div class="admin__field">
                            <label class="admin__field-label" for="status">
                                <span><?= __('Ticket ID') ?></span>
                            </label>
                            <div class="admin__field-control">
                                <span><?= $ticket->getCode() ?></span>
                            </div>
                        </div>
                    <?php endif; ?>
                    <div class="admin__field _required">
                            <label class="admin__field-label" for="Order number">
                                <span><?= __('Order number') ?></span>
                            </label>
                            <div class="admin__field-control">
                                <input type="text" name="order_number" class="required order_number" placeholder="enter order number of ticket"
                                       value="<?= $ticket->getOrderNumber() ?>">
                            </div>
                            <div class="order-error-number"></div>    
                    </div>
                    <div class="admin__field">
                        <label class="admin__field-label" for="status">
                            <span><?= __('Status') ?></span>
                        </label>
                        <div class="admin__field-control">
                            <select class="admin__control-select" name="status_id">
                                <?php foreach ($block->getStatusCollection() as $status): ?>
                                    <option value="<?= $status->getId() ?>" <?= $status->getId() == $ticket->getStatusId() ? 'selected' : '' ?>>
                                        <?= $status->getName() ?>
                                    </option>
                                <?php endforeach ?>
                            </select>
                        </div>
                    </div>
                    <div class="admin__field">
                        <label class="admin__field-label" for="priority">
                            <span><?= __('Priority') ?></span>
                        </label>
                        <div class="admin__field-control">
                            <select class="admin__control-select" name="priority_id">
                                <?php foreach ($block->getPriorityCollection() as $priority): ?>
                                    <option value="<?= $priority->getId() ?>" <?= $priority->getId() == $ticket->getPriorityId() ? 'selected' : '' ?>>
                                        <?= $priority->getName() ?>
                                    </option>
                                <?php endforeach ?>
                            </select>
                        </div>
                    </div>
                    <div class="admin__field">
                        <label class="admin__field-label" for="owner">
                            <span><?= __('Assignee') ?></span>
                        </label>
                        <div class="admin__field-control">
                            <select class="admin__control-select assignid" name="owner">
                                <?php foreach ($block->getAdminOwnerOptionArray() as $id => $name): ?>
                                    <option value="<?= $id ?>" <?= $id == $ticket->getOwner() ? 'selected' : '' ?>>
                                        <?= $name; ?>
                                    </option>
                                <?php endforeach; ?>
                            </select>
                        </div>
                    </div>
                    <input type="hidden" name="assign_id" id="assignid">
                    <div class="admin__field">
                        <label class="admin__field-label" for="subassign">
                            <span><?= __('Sub Assignee') ?></span>
                        </label>
                        <div class="admin__field-control">
                            <select class="admin__control-select" name="sub_assign">
                                <option selected="true" disabled="disabled"><?php echo __('-----Select sub assign-----')?></option>
                                <?php foreach ($subjectHelper->getAdminUsers() as $adminuser): ?>
                                    <option value="<?= $adminuser->getUserId() ?>" <?= $adminuser->getUserId() == $ticket->getSubAssign() ? 'selected' : '' ?>>
                                        <?= $adminuser->getUsername(); ?>
                                    </option>
                                <?php endforeach; ?>
                            </select>
                        </div>
                    </div>
                </div>
                <div class="section">
                    <div class="admin__fieldset-wrapper-title" tabindex="3">
                        <strong class="title">
                            <span><?= __('Additional Info') ?></span>
                        </strong>
                    </div>
                    <?php foreach ($block->getCustomFields() as $field): ?>
                        <div class="admin__field">
                            <?= $field->getLabelHtml(); ?>
                            <?= $field->getElementHtml(); ?>
                            <div class="note"><?= $field->getNote(); ?></div>
                        </div>
                    <?php endforeach; ?>
                </div>
            </div>
            <?php $histroyList = $subjectHelper->getAllHistroy($block->getTicket()->getId());?>
             <div class="additional_histroy">
               <div class="item-list">
                  <?php foreach($histroyList as $histroy):?>
                       <div class="item">
                        <span class="minor">
                          <?= __('added %1 (%2)', $subjectHelper->getNicetimeSpan($histroy->getCreatedAt()), $subjectHelper->formatDateTime($histroy->getCreatedAt())) ?>
                        </span>
                        <div class="histroy-content">
                        <?= $histroy->getTicketHistroy()?> 
                        </div> 
                       </div> 
                  <?php endforeach;?>
               </div>  
             </div>
        </div>

        <div class="main-col">
            <?php if ($block->getIsTicketLocked()): ?>
                <div class="hdmx__ticket-locked">
            <span>
                <?= __('You are not allowed to add the message to the current ticket as it is locked. To add the message to the current ticket you should change its status to one of unlocked.') ?>
            </span>
                </div>
            <?php else: ?>
            <div data-bind="scope: 'replyArea'">
                <!-- ko template: getTemplate() --><!-- /ko -->
                <script type="text/x-magento-init">
                    {
                        "*": {
                            "Magento_Ui/js/core/app": {
                                "components": {
                                    "replyArea": {
                                        "component": "Mirasvit_Helpdesk/js/reply-area",
                                        "config": {
                                            "field_html": <?= $block->getEditField(); ?>
                                        }
                                    },
                                    "replySwitcher": {
                                        "component": "Mirasvit_Helpdesk/js/reply-switcher",
                                        "config": <?= $block->getReplySwitcherJson(); ?>
                                    },
                                    "quickResponse": {
                                        "component": "Mirasvit_Helpdesk/js/quick-response",
                                        "config": <?= $block->getQuickRespoinsesJson(); ?>
                                    },
                                    "quickResponseBadges": {
                                        "component": "Mirasvit_Helpdesk/js/quick-response-badges",
                                        "config": <?= $block->getQuickRespoinsesJson(); ?>
                                    }
                                }
                            }
                        }
                    }
                </script>
            </div>

            <?php endif; ?>
            <?= $block->getChildHtml('helpdesk_messages'); ?>
        </div>

    </div>
</div>
<script type="text/javascript">
    var draftDelayPeriod = "<?php echo $block->getDraftInterval(); ?>";
    var draftUpdateUrl   = "<?php echo $block->getDrafUpdateUrl(); ?>";
    var draftTicketId    = "<?php echo $block->getTicket()->getId(); ?>";
    var isAllowDraft     = "<?php echo $block->isAllowDraft(); ?>";
    var draftText        = "<?php echo str_replace(["\n", '"'], ['NEW_LINE_SPR', '\"'], (string) $block->getDraftText()); ?>";

    draftText = draftText.replace(/NEW_LINE_SPR/g, "\n");
</script>

<style type="text/css">
  .additional_histroy .item {
    padding: 22px 2px 3px 24px;
  }
</style>
<script>
    //<![CDATA[
    require(['Mirasvit_Helpdesk/js/reply-update'], function () {});
    //]]>
</script>
<script type="text/javascript">
    require([
        "jquery",
        "jquery/ui"
        ], function($){
            $(document).ready(function(){

                var assignid = $('.admin__control-select.assignid').find(":selected").val();
                var foundassignid = assignid.substr(assignid.indexOf(' - ')+3,);
                if(foundassignid!=""){
                    $('#assignid').val(foundassignid);
                }
                
                $('.admin__control-select.assignid').on('change', function() {
                   var foundassignid = this.value.substr(this.value.indexOf(' - ')+3,);
                   if(foundassignid!=""){
                    $('#assignid').val(foundassignid);
                   }
                });

                $("input.order_number").keydown(function(){
                    checkOrderNumber(this.value);
                });
                $("input.order_number").keyup(function(){
                    checkOrderNumber(this.value);
                });
                function checkOrderNumber(orderNumber){
                    var AjaxUrl = "<?php echo $this->getUrl("customwork/index/checkorder");?>";
                    $.ajax({
                      type: 'POST',
                      dataType: 'json',
                      url: AjaxUrl,
                      data: {order_number:orderNumber},
                     }).done(function (data) {
                      if(data['data']['status']==true){
                        if($('span').hasClass('error-message')){
                           $('.error-message').remove();
                        }
                        $('.order-error-number').append('<span class="error-message" style="color:#e22626">This order number already exists</span>');
                      }else{
                        if($('span').hasClass('error-message')){
                           $('.error-message').remove();
                        }
                      } 
                    });
                }
            });
        });
</script>